### ISSUE TITLE
Can't Manage extension settings

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [code-cracker/code-cracker.github.io#10] opened 2015-09-16 13:01 UTC
I've installed Code Cracker as an extension for Visual Studio 2015, but there appears to be no way to manage which diagnostics are on and what levels they are on at. I've found the analyzers node of References in solution explorer. While I can make changes there they don't seem to save as the new set the next time I open the solution or project. Even if they did, this is installed for my entire VS2015, so I'd like to manage it at that level rather than have to make changes to every project I open.

**Comment by giggio** [comment] 2015-09-28 16:10
Duplicate of https://github.com/code-cracker/code-cracker/issues/524. Already discussing there.

**Closed as completed by giggio** 2015-09-28 16:10 UTC
